enum StatKeys { HEALTH, MOVEMENT_SPEED, JUMP_SPEED, GRAVITY, ATTACK_SPEED, ATTACK_DAMAGE }

const PLAYER_STATS = {
	StatKeys.HEALTH: 1000,
	StatKeys.MOVEMENT_SPEED: 100,
	StatKeys.JUMP_SPEED: 320,
	StatKeys.GRAVITY: 700,
	StatKeys.ATTACK_SPEED: 100,
	StatKeys.ATTACK_DAMAGE: 100
}
